// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Solution.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200403200303_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Cat", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Traits");

                    b.HasKey("CatId");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            Age = 3,
                            Gender = "Female",
                            Name = "Maddie",
                            Traits = "noisey"
                        },
                        new
                        {
                            CatId = 2,
                            Age = 11,
                            Gender = "Female",
                            Name = "Juno",
                            Traits = "playful"
                        },
                        new
                        {
                            CatId = 3,
                            Age = 12,
                            Gender = "Female",
                            Name = "Dano",
                            Traits = "bossy"
                        },
                        new
                        {
                            CatId = 4,
                            Age = 4,
                            Gender = "Male",
                            Name = "Baby",
                            Traits = "sleepy"
                        },
                        new
                        {
                            CatId = 5,
                            Age = 8,
                            Gender = "Male",
                            Name = "Lion",
                            Traits = "feisty"
                        });
                });

            modelBuilder.Entity("AnimalShelter.Models.Dog", b =>
                {
                    b.Property<int>("DogId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("Traits");

                    b.HasKey("DogId");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            DogId = 1,
                            Age = 3,
                            Gender = "Female",
                            Name = "Rilo",
                            Traits = "Maddie"
                        },
                        new
                        {
                            DogId = 2,
                            Age = 11,
                            Gender = "Female",
                            Name = "Mogley",
                            Traits = "playful"
                        },
                        new
                        {
                            DogId = 3,
                            Age = 12,
                            Gender = "Female",
                            Name = "Patricia",
                            Traits = "bossy"
                        },
                        new
                        {
                            DogId = 4,
                            Age = 4,
                            Gender = "Male",
                            Name = "Brownie",
                            Traits = "sleepy"
                        },
                        new
                        {
                            DogId = 5,
                            Age = 8,
                            Gender = "Male",
                            Name = "Rolf",
                            Traits = "feisty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
